"""
Pydantic Schemas for SmartHire GenAI
"""

from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field
from src.models.enums import ReviewStatus

class ExperienceItem(BaseModel):
    company: Optional[str] = Field(default=None, description="Company or organization name")
    role: Optional[str] = Field(default=None, description="Job title or role held")
    start_date: Optional[str] = Field(default=None, description="Start date (e.g. MM/YYYY or Year)")
    end_date: Optional[str] = Field(default=None, description="End date or 'Present'")
    description: Optional[str] = Field(default=None, description="Summary of responsibilities and achievements")
    technologies: List[str] = Field(default_factory=list, description="Technologies or tools used")

class EducationItem(BaseModel):
    institution: Optional[str] = Field(default=None, description="College, university, or school name")
    degree: Optional[str] = Field(default=None, description="Degree name (e.g. Bachelor of Science, Master of Science)")
    field: Optional[str] = Field(default=None, description="Field of study or major")
    start_date: Optional[str] = Field(default=None, description="Start year or date")
    end_date: Optional[str] = Field(default=None, description="Graduation year or date")

class ProjectItem(BaseModel):
    name: str = Field(description="Project title")
    description: Optional[str] = Field(default=None, description="Summary of what was built and achieved")
    technologies: List[str] = Field(default_factory=list, description="Tools, frameworks, and languages used")
    link: Optional[str] = Field(default=None, description="URL or repository link if present")

class ResumeProfile(BaseModel):
    """Structured candidate profile extracted from resume."""
    name: Optional[str] = Field(default=None, description="Candidate full name")
    email: Optional[str] = Field(default=None, description="Candidate email address")
    phone: Optional[str] = Field(default=None, description="Candidate phone number")
    location: Optional[str] = Field(default=None, description="City, State, or Country")
    skills: List[str] = Field(default_factory=list, description="List of technical and professional skills")
    experience: List[ExperienceItem] = Field(default_factory=list, description="Work experience history")
    education: List[EducationItem] = Field(default_factory=list, description="Educational background")
    certifications: List[str] = Field(default_factory=list, description="Certifications and licenses")
    projects: List[ProjectItem] = Field(default_factory=list, description="Notable projects")
    target_role: Optional[str] = Field(default=None, description="Target job title or primary career orientation")
    years_of_experience: Optional[float] = Field(default=None, description="Estimated total years of professional experience")
    summary: Optional[str] = Field(default=None, description="Professional summary or bio statement")

class HumanApprovedProfile(BaseModel):
    """Profile container enforcing Human-in-the-Loop review and audit tracking."""
    original_ai_profile: ResumeProfile
    approved_profile: ResumeProfile
    status: ReviewStatus = ReviewStatus.REQUIRES_REVIEW
    reviewed_at: Optional[str] = None
    change_summary: Optional[str] = None
    is_approved: bool = False

    def approve(self, edited_profile: Optional[ResumeProfile] = None):
        if edited_profile:
            self.approved_profile = edited_profile
            self.status = ReviewStatus.HUMAN_EDITED
        else:
            self.status = ReviewStatus.APPROVED
        self.is_approved = True
        self.reviewed_at = datetime.utcnow().isoformat()

    def reset_to_ai(self):
        self.approved_profile = self.original_ai_profile.model_copy(deep=True)
        self.status = ReviewStatus.REQUIRES_REVIEW
        self.is_approved = False
        self.change_summary = "Reset to original AI extraction."

class JobPosting(BaseModel):
    """Internal standardized representation of a job posting."""
    job_id: str
    title: str
    company: str
    location: str
    skills: List[str] = Field(default_factory=list)
    description: str
    source: str = "curated_dataset"

class JobMatchResult(BaseModel):
    """Match result combining job posting and semantic evaluation."""
    job: JobPosting
    similarity_score: float
    matched_skills: List[str] = Field(default_factory=list)
    missing_skills: List[str] = Field(default_factory=list)
    match_explanation: Optional[str] = None
    user_feedback: Optional[str] = None  # "relevant", "irrelevant", or None

class BulletCritique(BaseModel):
    original_bullet: str
    weakness_reason: str
    suggested_rewrite: str

class CVSuggestionResult(BaseModel):
    """Job-tailored CV improvements generated by Gemini."""
    target_job_id: str
    target_job_title: str
    target_company: str
    missing_skills: List[str] = Field(default_factory=list)
    weak_bullets: List[BulletCritique] = Field(default_factory=list)
    actionable_suggestions: List[str] = Field(default_factory=list)
    rewritten_summary: str
    rewritten_bullets: List[str] = Field(default_factory=list)
    grounding_notes: str = ""
    status: ReviewStatus = ReviewStatus.REQUIRES_REVIEW

class MentorCitation(BaseModel):
    source_title: str
    chunk_index: int
    snippet: str

    @property
    def document_title(self) -> str:
        return self.source_title

class MentorResponse(BaseModel):
    """Answer generated by AI Career Mentor with citations and reasoning."""
    question: str
    answer: str
    citations: List[MentorCitation] = Field(default_factory=list)
    is_grounded: bool = True
    refusal: bool = False
    thinking: Optional[str] = None

